### ISSUE TITLE
OR-Set should return set, not list

### ISSUE THREAD

**Issue by cmeiklejohn** [lasp-lang/types#23]
When `querying` the OR-Set, it should return a set, and not a list.

**Comment by cmeiklejohn** [comment]
@vitorenesduarte Is this something you can pickup?  I want to make sure the pure op-based implementation matches...

**Comment by vitorenesduarte** [comment]
@cmeiklejohn: what the spec should be? Right now is:

``` erlang
-spec query(state_orset()) -> [element()].
```

Which one do we want?

``` erlang
-spec query(state_orset()) -> ordsets:set()
-spec query(state_orset()) -> sets:set()
```

**Comment by cmeiklejohn** [comment]
No order; `sets:set().`

**Comment by vitorenesduarte** [comment]
Ok, I'll do that for the ones that are returning a list.

**Comment by vitorenesduarte** [comment]
https://github.com/lasp-lang/types/pull/33
