### ISSUE TITLE
Unknown type warnings in dialyzer

### ISSUE THREAD

**Issue by seancribbs** [lasp-lang/types#41]
Dialyzer complains about unknown types coming from this app:

```
Unknown types:
  ordsets:ordset/0
  type:crdt/0
  type:state_type/0
```

These come from the locations below:

``` shell
$ ag ordsets:ordset\|type:crdt\|type:state_type
src/ordsets_ext.erl
27:-spec equal(ordsets:ordset(), ordsets:ordset()) ->

src/state_gmap.erl
54:-type payload() :: {type:state_type(), orddict:orddict()}.

src/state_gset.erl
53:-type payload() :: ordsets:ordset().

src/state_twopset.erl
57:-type payload() :: {ordsets:ordset(), ordsets:ordset()}.

src/state_pair.erl
56:-type component() :: {type:state_type(), type:crdt()}. %% @todo
67:-spec new([type:state_type()]) -> state_pair().
```

NB: I am using OTP 18.3.

**Comment by seancribbs** [comment]
Update: The only one that is actually erroneous is `ordsets:ordset/0`, instead it should be `ordsets:ordset(any())` or with an unbound type variable like `ordsets:ordset(T)`.

**Comment by vitorenesduarte** [comment]
Can you see if #42 solves it?

**Comment by seancribbs** [comment]
I now get:

```
Unknown types:
  type:crdt/0
  type:state_type/0
```

It seems the types defined in `type.erl` are not exported with `-export_type([...])`. Any type used outside that module should be exported (and the same with other modules that have types referred to elsewhere).

**Comment by vitorenesduarte** [comment]
Thank you. We are running the dialyzer (I think) but it's not catching these.
Maybe the last commit solves it.

**Comment by seancribbs** [comment]
I still get those unknown type warnings. I'm going to investigate more about my environment and app to make sure it's not something I'm doing wrong. Thanks!

**Comment by vitorenesduarte** [comment]
Can you try again?
Sorry for the trouble.

**Comment by seancribbs** [comment]
The last commit fixes it, thank you!

**Comment by vitorenesduarte** [comment]
Cool. It's merged.
Thanks
