### ISSUE TITLE
Unified API for Registers

### ISSUE THREAD

**Issue by vitorenesduarte** [lasp-lang/types#61]
- `pure_mvregister` uses `{set, value()}`
- `state_mvregister` uses `{set, value()}`
- `state_lwwregister` uses `{set, timestamp(), value()}`

In `state_lwwregister`, the operation was extended to `{set, timestamp(), value()}` because we also need to supply a timestamp.

Should `pure_mvregister` and `state_mvregister` operations be extended as well (and in that case they would ignore the timestamp) or there's a better approach?

Note: both `state_lwwregister` and `state_mvregister` are implemented in #60

**Comment by vitorenesduarte** [comment]
Also, `state_mvregister` demands CRDTs as values, while in `state_lwwregister` and `pure_mvregister` we can have anything.
- `state_mvregister` ([link](https://github.com/lasp-lang/types/blob/causal_crdts/src/state_mvregister.erl#L52))
- `state_lwwregister` ([link](https://github.com/lasp-lang/types/blob/causal_crdts/src/state_lwwregister.erl#L60))
- `pure_mvregister` ([link](https://github.com/lasp-lang/types/blob/causal_crdts/src/pure_mvregister.erl#L49))

This is basically because **DotFun** demands \join to be defined in the values, in order to merge two **DotFun**'s.
(see **MVRegister** and **DotFun** definition [here](https://arxiv.org/pdf/1603.01529v1.pdf))

Not sure how to proceed on this one.

**Comment by cmeiklejohn** [comment]
For now, I personally would not bother unifying the APIs until we have a reason to perform all of that work.

**Comment by vitorenesduarte** [comment]
I did it on #60
Should revert it?

**Comment by cmeiklejohn** [comment]
No, if you already did the work, that's fine.
