### ISSUE TITLE
make type representation a tagged tupple 

### ISSUE THREAD

**Issue by ghost** [lasp-lang/types#89]
for example - `dot_set.erl` : 

Rather than : 

```erlang
-spec new() -> dot_set().
new() ->
   ordsets:new().
```
Instead do : 

```erlang
-spec new() -> {module(), dot_set()}.
new() ->
   {dot_set, ordsets:new()}.
```
This would make it easier to expose them at the web layer, rather than having to add type specific code paths, in particular I'm thinking of meta programming such as Elixir macros/protocols.

I know a change like this is crazy at this stage, but putting it out there for discussion.

For the use cases I have in mind, an alternative would be to wrap each type but that's a lot of bloat.

**Comment by cmeiklejohn** [comment]
All of the data types are already tagged tuples.  You're looking at one of the support structures, that's not meant to be used directly.
